### ISSUE TITLE
Issues with getFromScreen

### ISSUE THREAD

**Issue by cdc143** [cdc143/CPSC-599#7]
Check dropLoop for code. I'm loading two random numbers (0-15) into x and y, but calling getFromScreen with those arguments seems to crash everything. I've commented out the offending lines. Maybe I'm calling it wrong, but it might be a sign of a glitch somewhere in there

**Comment by cdc143** [comment]
Also, looking at Kierstens latest notes, it seems there's some issues with getting the enemies moving. Probably a related bug somewhere else (might be in the old code that needs to be rewritten anyway). Our prg file is currently 2077 bytes, and we have 3583 available on the VIC, so we shouldn't be out of memory. The additional 4 levels should take no more than 500 bytes total, so that leaves us with ~1kb to do everything else. That number is also kind of low, because as all the drawing and collision stuff is converted, the prg will become smaller as well.

**Comment by ksmort** [comment]
I fixed the problems I was getting with the drawing, but the screen bugs out from time to time, but that is probably another bug/pushing and pulling from the stack or something.  

If you take a look at the branch I'm working on, so that I don't upload a zillion files to the master branch, demo 02-4 now has movement and (very basic) collision detection working.

**Comment by cdc143** [comment]
Oh awesome! I'm just working on drawing out a few new levels, so those should be ready to go soon. I know we had the collision animation knocking the player backwards, but with some of my levels (which are like narrow corridors) do you think we should just have the character flash and be like invincible for a couple seconds? Cause otherwise if they don't have a sword, they'll just keep having to run into the enemy and die if that's the only way they can go.

**Comment by ksmort** [comment]
Sweet!  That sounds like a good idea!  Otherwise it might get painful to code that animation.

I added the title page (well, blank screen at the moment) back into the code and incorporated the timer into the getRandom function (x and y registers are preserved, so just pretend like nothing has changed) so that enemies now spawn at random locations right off the bat.  Enemies are also now different colours, randomly assigned (for killing them, can have a check so that when an enemy colour is less than #$0a, they're dead.  Or, since black is invisible (more difficult), could have enemies increase in colour so that when they reach something like #80, they die).

Screen kind of blows up after excess refreshing, but still alright.
